# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://hub.fastgit.xyz/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://hub.fastgit.xyz/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
